export const merchItems = [
    {
        name: 'BYTE BRIMS',
        type: 'HATS',
        price: 175.0,
        images: [
            '/images/temp-merch.png',
            '/title-header.png',
            '/images/temp-merch.png',
        ],
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        colors: ['#FF0000', '#00FF00', '#0000FF'],
        isBestSeller: true,
    },
    {
        name: 'TECH TOTES',
        type: 'TOTE BAG',
        price: 150.0,
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        images: ['/images/tote-bag.png', '/title-header.png'],
        colors: ['#FF0000', '#0000FF'],
        isBestSeller: false,
    },
    {
        name: 'T-SHIRTS',
        type: 'SHIRTS',
        price: 250.0,
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        images: ['/images/shirt.png', '/title-header.png', '/images/shirt.png'],
        colors: ['#111120', '#41A01E', '#FFFFFF'],
        isBestSeller: true,
    },
    {
        name: 'HATS',
        type: 'HATS',
        price: 175.0,
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        images: ['/images/hat.png'],
        colors: ['#FF0000'],
        isBestSeller: true,
    },
    {
        name: 'BYTE BRIMS 2',
        type: 'HATS',
        price: 175.0,
        images: [
            '/images/temp-merch.png',
            '/title-header.png',
            '/images/temp-merch.png',
        ],
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        colors: ['#FF0000', '#00FF00', '#0000FF'],
        isBestSeller: true,
    },
    {
        name: 'T-SHIRTS 2',
        type: 'SHIRTS',
        price: 250.0,
        images: ['/images/shirt.png', '/title-header.png', '/images/shirt.png'],
        sizes: ['Small', 'Medium', 'Large', 'Extra-Large'],
        colors: ['#111120', '#41A01E', '#FFFFFF'],
        isBestSeller: true,
    },
]
