export const officers = [
    {
        firstName: 'BAZER TIMOTHY',
        lastName: 'NUÑEZ',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341903/bazer_cap0rb.png)',
        role: 'Executive Director',
        yearLevel: 3,
    },
    {
        firstName: 'TRISHIA MAE',
        lastName: 'BASMAYOR',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341907/trishia_ocyncr.png)',
        role: 'Secretary',
        yearLevel: 2,
    },
    {
        firstName: 'CHRISTIAN JAMES',
        lastName: 'BAYADOG',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341905/cj_abmkdj.png)',
        role: 'Co-Finance: Treasurer',
        yearLevel: 2,
    },
    {
        firstName: 'CEFERINO',
        lastName: 'JUMAO-AS V',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341903/ceferino_ilnr4m.png)',
        role: 'Co-Finance: Auditor',
        yearLevel: 2,
    },
    {
        firstName: 'ISHAH NICHOLEI',
        lastName: 'BAUTISTA',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341904/ishah_wnq7bx.png)',
        role: 'Marketing Director',
        yearLevel: 2,
    },
    {
        firstName: 'CHRISTINE MAE',
        lastName: 'BAGAZIN',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341904/christine_xx93qp.png)',
        role: 'Partnerships & Linkages Director',
        yearLevel: 3,
    },
    {
        firstName: 'MON ANDREW',
        lastName: 'RETUYA',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341906/mon_n4iwsx.png)',
        role: 'Communication & Logistics Director',
        yearLevel: 3,
    },
    {
        firstName: 'JAMES GABRIEL',
        lastName: 'ELIJAH TY',
        image: 'url(https://res.cloudinary.com/dc7anycov/image/upload/v1723341905/james_ouxr7t.png)',
        role: 'Education & Development Director ',
        yearLevel: 2,
    },
]
